# Generated by Django 5.0.3 on 2024-11-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0002_points_p_agentbal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='w_stakecom_bal',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='w_stakecom_claim',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
