# Generated by Django 5.0.3 on 2024-11-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0003_userwallet_w_stakecom_bal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='f_revert',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
