# Generated by Django 5.0.3 on 2024-12-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0008_alter_userprofile_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='g_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
