# Generated by Django 5.0.3 on 2024-12-04 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0010_alter_userprofile_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='g_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='games',
            name='g_update',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
