# Generated by Django 5.0.3 on 2024-12-04 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0011_alter_games_g_created_alter_games_g_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='f_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='fight',
            name='f_update',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='fighthistory',
            name='f_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='fighthistory',
            name='f_update',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
