# Generated by Django 5.0.3 on 2024-12-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0020_alter_userwallet_w_dateupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='f_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fight',
            name='f_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
