# Generated by Django 5.0.3 on 2024-12-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0021_alter_fight_f_created_alter_fight_f_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='convertrewards',
            name='r_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fighthistory',
            name='f_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fighthistory',
            name='f_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='g_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='g_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='longestfight',
            name='l_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='points',
            name='p_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='points',
            name='p_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stakefund',
            name='s_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='w_dateupdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='uwalletcashout',
            name='cw_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
