# Generated by Django 5.0.3 on 2024-12-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0022_alter_bet_created_alter_convertrewards_r_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='f_mpout',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='fight',
            name='f_wpout',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
