# Generated by Django 5.0.3 on 2024-12-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0023_fight_f_mpout_fight_f_wpout'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='f_prevwin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
