# Generated by Django 5.0.3 on 2024-12-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0024_fight_f_prevwin'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='coutstat',
            field=models.IntegerField(default=0),
        ),
    ]
