# Generated by Django 5.0.3 on 2024-12-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0025_useraccount_coutstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='coutstat',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
