# Generated by Django 5.0.3 on 2024-12-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0026_alter_useraccount_coutstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='commission_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='default_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
    ]
