# Generated by Django 5.0.3 on 2024-12-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0027_alter_userwallet_commission_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controls',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(blank=True, max_length=50, null=True)),
                ('c_status', models.IntegerField(default=0)),
                ('c_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
