# Generated by Django 5.0.3 on 2024-12-11 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0029_subcription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcription',
            name='s_by',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcription',
            name='s_movie',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='ugs_app.games'),
        ),
    ]
