# Generated by Django 5.0.3 on 2024-12-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0030_alter_subcription_s_by_alter_subcription_s_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='dummy',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
