# Generated by Django 5.0.3 on 2024-12-19 06:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0031_useraccount_dummy'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieWallet',
            fields=[
                ('m_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('m_balance', models.IntegerField(default=0)),
                ('m_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieWallet_Logs',
            fields=[
                ('ml_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ml_amount', models.IntegerField(default=0)),
                ('ml_type', models.CharField(choices=[('SUBSCRIBE', 'SUBSCRIBE'), ('DONATE', 'DONATE')], max_length=50, null=True)),
                ('ml_date', models.DateTimeField(auto_now_add=True)),
                ('ml_movie', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='ml_movie', to='ugs_app.games')),
                ('ml_player', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, related_name='watcher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': ('-ml_date',),
            },
        ),
    ]
