# Generated by Django 5.0.3 on 2024-11-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staking_app', '0002_stake_claimed_comms'),
    ]

    operations = [
        migrations.AddField(
            model_name='stake_claimed_comms',
            name='sr_confirmed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stake_claimed_comms',
            name='sr_dateconfirm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
