"""
Django settings for ugs_proj project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import sys
import secrets

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

TIME_ZONE='Asia/Manila' 
USE_I18N = True
USE_L10N = True
USE_TZ = True
# TIME_ZONE = 'UTC'
# USE_L10N = True
# USE_TZ = True




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-ard^dr15f8bucl+ml=s)g@4g^ck&8s5!5ys+l&9$cwf^1n(7d2'
SECRET_KEY =os.getenv('SECRET_KEY','django-insecure-ard^dr15f8bucl+ml=s)g@4g^ck&8s5!5ys+l&9$cwf^1n(7d2')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

DEBUG =os.getenv('DEBUG','True') == 'True'

# ALLOWED_HOSTS = ["*"]

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS','127.0.0.1,localhost,ugs2026.com').split(',')



# CORS_ALLOW_CREDENTIALS =True
# CORS_ALLOW_CREDENTIALS=os.getenv('CORS_ALLOW_CREDENTIALS','True') == 'True'

# CORS_ALLOW_ALL_ORIGINS = True
# CORS_ALLOW_ALL_ORIGINS=os.getenv('CORS_ALLOW_ALL_ORIGINS','True') == 'True'


AUTH_USER_MODEL = 'ugs_app.UserProfile'

# Application definition

INSTALLED_APPS = [
    'ugs_app.apps.UgsAppConfig',
    'staking_app.apps.StakingAppConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
  
    'corsheaders',
    'django.contrib.humanize',
    'django_minify_html',
    'django_hide',
    'csp',
    'compressor',
   
]


STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',

    # Add this
    'compressor.finders.CompressorFinder',
)


MIDDLEWARE = [
    # 'django.middleware.gzip.GZipMiddleware', #This one
    # 'htmlmin.middleware.HtmlMinifyMiddleware', #This one
    # 'htmlmin.middleware.MarkRequestMiddleware', #This one

    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django_hide.middleware.CSRFHIDEMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'csp.middleware.CSPMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_minify_html.middleware.MinifyHtmlMiddleware',
    'ugs_app.middleware.ReferrerPolicyMiddleware',
]


# X_FRAME_OPTIONS = 'ALLOWALL'

nonce = secrets.token_urlsafe(16)

CSP_FRAME_SRC = [
    "'self'",                # Allow same-origin
    "https://194sabong.site",
    "https://xstream-taiwan.site",
      "https://c1.streamhub25.site",
      "https://vimaxxxx11.b-cdn.net",
        "'unsafe-inline'" ,
          "*"  # Allow the specific external site
]

CSP_STYLE_SRC_ATTR = [
    "'self'",                    # Allow styles from your own domain
   "https://194sabong.site", 
     "https://xstream-taiwan.site", 
           "https://c1.streamhub25.site", 
                "https://vimaxxxx11.b-cdn.net" ,    # Allow specific external domain(s)
    "'unsafe-inline'"  
           # Allow inline styles (if necessary)
]


CSP_DEFAULT_SRC = [
    "'self'",
    "'unsafe-inline'",
    "'unsafe-inline'"
    ]

CSP_IMG_SRC = [
    "'self'",
    "data:",  # Allow data URIs for images
    # Add any other trusted sources for images
]
CSP_SCRIPT_SRC = [
    "'self'",
    "https://code.jquery.com", 
    "https://cdn.jsdelivr.net", 
      "https://194sabong.site",
      "https://c1.streamhub25.site",
      "https://vimaxxxx11.b-cdn.net",
      "'unsafe-inline'"  
      ]


CSP_STYLE_SRC = [
    "'self'",
    "https://194sabong.site",
    "https://c1.streamhub25.site",
     "https://vimaxxxx11.b-cdn.net",
    "'unsafe-inline'"
    ]  # General style sources

CSP_STYLE_SRC_ELEM = [
    "'self'",     
    "https://194sabong.site", 
    "https://c1.streamhub25.site",               # Allow styles from your own domain
    "https://fonts.googleapis.com",        # Allow specific external domains
    "https://cdnjs.cloudflare.com", 
     "https://vimaxxxx11.b-cdn.net",
     "'unsafe-inline'"  
]

CSP_SCRIPT_SRC_ELEM = [
    "'self'",                             # Allow scripts from your own domain
    "https://cdnjs.cloudflare.com",       # Allow scripts from a CDN
    "https://code.jquery.com", 
    "https://194sabong.site",
    "https://c1.streamhub25.site",
     "https://vimaxxxx11.b-cdn.net",
    "'unsafe-inline'"  
]

CSP_FONT_SRC = [
    "'self'",                     # Allow fonts from your own domain      # Replace with the correct domain for your font files
    "https://fonts.googleapis.com",  # If you are using Google Fonts
    "https://fonts.gstatic.com",
      "https://fonts.bunny.net",  # If you are using Google Fonts
    "'unsafe-inline'"
]



ROOT_URLCONF = 'ugs_proj.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ugs_proj.wsgi.application'
ASGI_APPLICATION = 'ugs_proj.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASE_URL =os.getenv('DATABASE_URL', None)


if not DATABASE_URL:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'ugs_db',
            'USER': 'root',
            'PASSWORD':'Kinsee_06',
            'HOST':'localhost',
            'PORT':'3306',
        }
    }
else:
    DATABASES = {
    #    'default': {
    #         'ENGINE':'django.db.backends.postgresql',
    #         'NAME': os.getenv('DB_NAME'),
    #         'USER': os.getenv('DB_USER'),
    #         'PASSWORD': os.getenv('DB_PASSWORD'),
    #         'HOST': os.getenv('DB_HOST'),
    #         'PORT':os.getenv('DB_PORT'),
    #         'OPTIONS':{'sslmode': 'require'},
    #     }
    'default': {
            'ENGINE':'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT':os.getenv('DB_PORT'),
            # 'OPTIONS':{'sslmode': 'require'},
        }
    }


CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG':{
            'hosts': [('127.0.0.1', 6379)],
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# STATIC_URL = 'static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# STATICFILES_DIRS = [os.path.join(BASE_DIR, "static/")]
# MEDIA_URL = 'uploads/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads/')


# STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'ugs_app/static/'),
    os.path.join(BASE_DIR, 'uploads'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage' 

MEDIA_URL = '/uploads/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')



CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': '127.0.0.1:11211',
    }
}


COMPRESS_ENABLED = True
COMPRESS_CSS_HASHING_METHOD = 'content'
COMPRESS_FILTERS = {
    'css':[
        'compressor.filters.css_default.CssAbsoluteFilter',
        'compressor.filters.cssmin.rCSSMinFilter',
    ],
    'js':[
        'compressor.filters.jsmin.JSMinFilter',
    ]
}
HTML_MINIFY = True
KEEP_COMMENTS_ON_MINIFYING = True

# STATICFILES_DIRS = (
#     os.path.join(BASE_DIR, 'uploads'),
#     )
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# RECAPTCHA_PUBLIC_KEY = '6Ld3iA8qAAAAABXPe2MdSf4htmxTJq4mdKjqbMvM'
# RECAPTCHA_PRIVATE_KEY = '6Ld3iA8qAAAAAMh29MY2cpYxj9mqqgT8vGUh9-5L'
